import { Metadata } from "next";
import Navigation from "@components/nav";

export const metadata: Metadata = {
  title: { default: "App", template: "%s | My Website" },
  description: "Generated by Next.js",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
